[package]
name = "minus-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
minus-core = { path = "../minus-core" }
minus-api = { path = "../minus-api" }
minus-db = { path = "../minus-db" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
