[package]
name = "minus-provider-openrouter"
version = "0.1.0"
edition = "2021"

[dependencies]
minus-api = { path = "../../crates/minus-api" }
minus-provider-openai = { path = "../minus-provider-openai" }
anyhow = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
