[package]
name = "minus-channel-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
minus-api = { version = "0.1.0", path = "../../crates/minus-api" }
minus-core = { path = "../../crates/minus-core" }
minus-db = { path = "../../crates/minus-db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
futures = "0.3"
rand.workspace = true
chrono.workspace = true
uuid.workspace = true
toml.workspace = true
